# Generated by Django 4.1.2 on 2024-07-07 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_message_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='photo',
        ),
    ]
