name: Deploy Jekyll to GitHub Pages

on:
  push:
    branches:
      - "main"  # Trigger the workflow on pushes to the main branch

  workflow_dispatch:  # Allows the workflow to be manually triggered from the Actions tab

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4  # Checkout the repository contents

      - name: Set up Ruby (Jekyll dependencies)
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1  # Specify the Ruby version required by Jekyll
          bundler-cache: true  # Use bundler cache for faster builds

      - name: Install Dependencies
        run: |
          bundle install  # Install Jekyll and other dependencies

      - name: Build the Jekyll Site
        run: |
          bundle exec jekyll build --source ./ --destination ./_site  # Build the site

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./_site  # Upload the built site files as an artifact

  # Deployment job
  deploy:
    runs-on: ubuntu-latest
    needs: build  # Ensure the deploy job runs after the build job
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4  # Checkout the repository contents again for deployment

      - name: Configure Pages
        uses: actions/configure-pages@v5  # Configure GitHub Pages deployment

      - name: Download Artifact
        uses: actions/download-pages-artifact@v3
        with:
          artifact_name: _site  # Download the built site files for deployment

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4  # Deploy the site to GitHub Pages
        with:
          branch: gh-pages  # Specify the branch for GitHub Pages (typically gh-pages)
          folder: _site  # Folder containing the built site files
